Feat/autopublish
secvisogram/csaf-cms-backend pull request #173
Opened 2023-10-26 09:27 UTC by mfd2007

A first draft for #88 to have an time based publication of an advisory.

New status "AutoPublish" has been added. You can now switch from "RfPubication" to "Autopublish" or manually "Published".

To do's
- [ ] Add tests
- [ ] Update documentation

2025-05-02 12:03 UTC, tschmidtb51 commented
> Not at the moment. We will discuss the issue in our next status meeting.

@mfd2007 will work on this again.

2025-10-06 11:15 UTC, rainer-exxcellent requested changes
Could you please rebase the branch onto the current main?

2025-10-08 09:01 UTC, mfd2007 commented
> Could you please rebase the branch onto the current main?

I will rebase after #206 is merged.

2025-11-19 14:58 UTC, mfd2007 commented
I rebased the code on the current `main`.

Tests are still missing, but documents are automatically published on the trusted provider.

2026-06-16 07:18 UTC, bendo-eXX commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishConfig.java
> +        Collection<GrantedAuthority> authorities = AuthorityUtils.createAuthorityList("ROLE_publisher", "ROLE_auditor", "ROLE_registred");
Typo: ROLE_registered

2026-06-16 07:18 UTC, bendo-eXX commented on src/main/resources/application.properties
> +csaf.autoPublish.enableInsecureTLS=${CSAF_AUTOPUBLISH_INSECURETLS:true}
Shouldn't `enableInsecureTLS` be set to `false` by default?

In my view, that would be the more secure default setting. Anyone who needs insecure TLS connections can enable this explicitly.

2026-06-16 07:18 UTC, bendo-eXX commented on src/main/resources/application.properties
> +csaf.autoPublish.cron=${CSAF_AUTOPUBLISH_CROM:0 * * * * *}
Typo: should be CSAF_AUTOPUBLISH_CRON

2026-06-16 07:18 UTC, bendo-eXX commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishJob.java
> +          Path p = this.advisoryService.exportAdvisory(advisory.getAdvisoryId(), ExportFormat.JSON);
The `Files.createTempFile()` function in `exportAdvisory()` creates a file in the `/tmp` directory, which is not currently being deleted.

A `Files.deleteIfExists(path)` call within a `finally` block following the WebClient call would probably be a good idea to ensure the temporary file is reliably deleted.

2026-06-16 07:18 UTC, bendo-eXX commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishJob.java
> +  private static final Logger LOG = LoggerFactory.getLogger(AdvisoryController.class);
The logger has been initialised with the wrong class.

2026-06-16 07:18 UTC, bendo-eXX commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishJob.java
> +// TODO Check, if still needed for exception handling
Commented-out code should either be uncommented or removed before merging.

2026-06-24 07:46 UTC, mfd2007 commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishConfig.java
> +        Collection<GrantedAuthority> authorities = AuthorityUtils.createAuthorityList("ROLE_publisher", "ROLE_auditor", "ROLE_registred");
fixed

2026-06-24 07:46 UTC, mfd2007 commented on src/main/resources/application.properties
> +csaf.autoPublish.enableInsecureTLS=${CSAF_AUTOPUBLISH_INSECURETLS:true}
fixed

2026-06-24 07:46 UTC, mfd2007 commented on src/main/resources/application.properties
> +csaf.autoPublish.cron=${CSAF_AUTOPUBLISH_CROM:0 * * * * *}
fixed

2026-06-24 07:50 UTC, mfd2007 commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishJob.java
> +  private static final Logger LOG = LoggerFactory.getLogger(AdvisoryController.class);
fixed

2026-06-24 07:50 UTC, mfd2007 commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishJob.java
> +// TODO Check, if still needed for exception handling
removed

2026-06-24 09:03 UTC, mfd2007 commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/task/PublishJob.java
> +          Path p = this.advisoryService.exportAdvisory(advisory.getAdvisoryId(), ExportFormat.JSON);
added a finally block.

2026-06-24 09:11 UTC, tommylehmann commented
Good to see there is traction again on this feature. Two Notes on the current implementation to keep in mind.
1. the proposed csaf-trusted-provider setup in gocsaf uses an reverse proxy with x.509 certificates to gate access to the trusted-provider cgi. So the autopublish feature should support that. Probably the reason you added csaf_uploader go binary, I think
2. even if its possible personally I don't like having a GPG private key on a public server even if its passphrase secured. From my point of view it would be better to let csaf_uploader handle the signature, handle the signature in csaf-backend or implement a remote credential provider like hashicorp vault, openboa.

2026-06-24 09:31 UTC, mfd2007 commented
> Good to see there is traction again on this feature. Two Notes on the current implementation to keep in mind.
> 
>     1. the proposed csaf-trusted-provider setup in gocsaf uses an reverse proxy with x.509 certificates to gate access to the trusted-provider cgi. So the autopublish feature should support that. Probably the reason you added csaf_uploader go binary, I think

The uploader was added just for the setup process of the test environment. The upload-task does an POST to the cgi of the trusted provider. To be honest I wanted to avoid to add the tls client authentication in the first step.

>     2. even if its possible personally I don't like having a GPG private key on a public server even if its passphrase secured. From my point of view it would be better to let csaf_uploader handle the signature, handle the signature in csaf-backend or implement a remote credential provider like hashicorp vault, openboa.

My primary goal for now is to add the basic functionality. Then I can look into TLS client authentication.

Integrating PGP for signing (especially with the desired support for a hardware token as mentioned in the discussion to the uploader) will be difficult.

2026-06-29 05:55 UTC, rainer-exxcellent requested changes
The branch needs a rebase again

2026-07-08 06:16 UTC, bendo-eXX commented on .gitattributes
> +docker/container/trustedprovider/fcgiwrap text eol=lf
typo: ‘fcgiwarp’ instead of ‘fcgiwrap’

2026-07-08 07:04 UTC, bendo-eXX commented on docker/data/cms-db/shards/00000000-7fffffff/_replicator.1759840210.couch
The files in `data/cms-db/shards/`, as well as `dbs.couch` and `nodes.couch`, are CouchDB runtime data and should not be included in the repository. They are generated automatically when the Docker container starts (volume mount in `compose.yaml`).

This is caused by a typo in data/cms-db/.gitignore:
typo: ‘shrads/*’ instead of ‘shards/*’

2026-07-08 07:15 UTC, bendo-eXX commented on src/main/java/de/bsi/secvisogram/csaf_cms_backend/service/AdvisoryService.java
> +                	throw new CsafException("TLP-Level missing", CsafExceptionKey.AdvisoryValidationError);
I would suggest adding a ‘Bad Request’ status code and including the error message in the response body within the controller. That way, in the event of an error, the front end will not receive a 404, but a 400 Bad Request with the relevant error message in the response body.

2026-07-08 12:20 UTC, bendo-eXX submitted a review, later dismissed
LGTM

2026-07-08 12:22 UTC, rainer-exxcellent submitted a review, later dismissed
LGTM

2026-07-10 08:57 UTC, bendo-eXX approved these changes

2026-07-10 10:47 UTC, merged