fix: Add OIDC-URL env variable
secvisogram/csaf-cms-backend pull request #198
Opened 2024-08-27 09:12 UTC by mfd2007

Added a additional env variable to be more flexible.

2025-01-27 12:28 UTC, mfd2007 commented
Problem is decribed in #99. There was an inadvertent reference to PR #195.

2025-01-28 12:52 UTC, rainer-exxcellent requested changes
I like the solutions but I think the pull request is only marginally related to the issue #/99

2025-01-28 12:52 UTC, rainer-exxcellent commented on .env.example
>  CSAF_KEYCLOAK_EXTERNAL_PROTOCOL=http
I think we can remove the variables  CSAF_KEYCLOAK_EXTERNAL_PROTOCOL, CSAF_KEYCLOAK_EXTERNAL_HOSTNAME and CSAF_KEYCLOAK_EXTERNAL_PORT as they are no longer needed

2025-01-28 15:50 UTC, mfd2007 commented on .env.example
>  CSAF_KEYCLOAK_EXTERNAL_PROTOCOL=http
Yes, I removed the variables.

2025-01-28 16:06 UTC, mfd2007 commented
> I like the solutions but I think the pull request is only marginally related to the issue #/99

You are right. We should merge this PR and I will look for the solution of #99 .

2025-04-07 12:59 UTC, rainer-exxcellent approved these changes
LGTM

2025-05-02 04:40 UTC, merged